project_name: "financial_fraud_detection"

hypergraph:
  construction_mode: "static" # Structure transactionnelle fixe
  node_dim: 64 # Dimensions réduites pour la vitesse

model:
  architecture: "RHT"
  hidden_dim: 128
  
  pente:
    temporal_dim: 16 # Suffisant pour timestamps simples
    volume_dim: 32 # Important pour les montants agrégés
    use_attention: false # Concaténation plus rapide

training:
  epochs: 10
  batch_size: 1024 # Gros batchs pour le volume massif
  alpha_task: 10.0 # Priorité à la classification (Fraude/Non-Fraude)
